# render.yaml - Optional: Infrastructure as Code
services:
  - type: web
    name: wildfire-prediction-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PYTHON_ENV
        value: production
      - key: PORT
        value: 10000
    buildCommand: ""
    startCommand: ""  # Defined in Dockerfile
    disk:
      name: models
      mountPath: /app/models
      sizeGB: 1
